<script setup lang="ts">
definePageMeta({middleware:['auth']})
const supabase=useSupabaseClient(); const {company,profile,loadProfile,resolveAuthenticatedUser}=useProfile()
const form=reactive<any>({name:'',abn:'',email:'',phone:'',website:'',address_line1:'',address_line2:'',city:'',state_region:'',postcode:'',country_code:'AU',logo_url:''})
const loading=ref(false), message=ref(''), errorMessage=ref(''); const logoFile=ref<File|null>(null)
onMounted(async()=>{await loadProfile(); Object.assign(form,company.value||{})})
const onLogo=(e:any)=>logoFile.value=e.target.files?.[0]||null
const save=async()=>{loading.value=true;message.value='';errorMessage.value='';try{
 const authUser=await resolveAuthenticatedUser()
 const userId=authUser?.id
 if(!isValidUuid(userId)) throw new Error('Unable to verify your signed-in session. Please reload the page and try again.')
 let companyId=isValidUuid(company.value?.id)?company.value.id:null
 if(!companyId){const {data:newCompany,error:createErr}=await supabase.from('companies').insert({name:form.name,type:profile.value?.role==='supplier'?'supplier':'repairer',country_code:form.country_code||'AU',owner_user_id:userId,email:form.email||authUser?.email}).select('id').single();if(createErr)throw createErr;companyId=newCompany.id;const {error:profileErr}=await supabase.from('profiles').update({company_id:companyId}).eq('id',userId);if(profileErr)throw profileErr;await loadProfile()}
 let logo=form.logo_url
 if(logoFile.value){const ext=logoFile.value.name.split('.').pop();const path=`${userId}/logo-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('company-logos').upload(path,logoFile.value,{upsert:true});if(error)throw error;logo=supabase.storage.from('company-logos').getPublicUrl(path).data.publicUrl}
 const {error}=await supabase.from('companies').update({...form,logo_url:logo,updated_at:new Date().toISOString()}).eq('id',companyId!);if(error)throw error;await loadProfile();Object.assign(form,company.value||{});message.value='Company profile saved.'
 }catch(e:any){errorMessage.value=e.message||'Unable to save company.'}finally{loading.value=false}}
</script>
<template><section class="section"><div class="container" style="max-width:900px;"><div class="kicker">Account</div><h1 class="page-title" style="margin-top:8px;">Company Profile</h1><p class="muted">{{profile?.role==='supplier'?'Parts Supplier':'Smash Repairer'}} company details</p><form class="card" style="padding:24px;margin-top:22px;" @submit.prevent="save"><div v-if="message" class="notice success">{{message}}</div><div v-if="errorMessage" class="notice error">{{errorMessage}}</div><div class="grid grid-2"><div><label class="label">Company name</label><input v-model="form.name" class="input" required></div><div><label class="label">ABN / Business number</label><input v-model="form.abn" class="input"></div><div><label class="label">Email</label><input v-model="form.email" class="input" type="email"></div><div><label class="label">Phone</label><input v-model="form.phone" class="input"></div><div><label class="label">Website</label><input v-model="form.website" class="input"></div><div><label class="label">Country code</label><input v-model="form.country_code" class="input" maxlength="2"></div><div><label class="label">Address</label><input v-model="form.address_line1" class="input"></div><div><label class="label">Address line 2</label><input v-model="form.address_line2" class="input"></div><div><label class="label">City</label><input v-model="form.city" class="input"></div><div><label class="label">State / Region</label><input v-model="form.state_region" class="input"></div><div><label class="label">Postcode</label><input v-model="form.postcode" class="input"></div><div><label class="label">Company logo</label><input class="input" type="file" accept="image/*" @change="onLogo"></div></div><div v-if="form.logo_url" style="margin-top:18px;"><img :src="form.logo_url" alt="Company logo" style="max-width:180px;max-height:90px;object-fit:contain;border-radius:12px;"></div><button class="btn btn-primary" style="margin-top:20px;" :disabled="loading">{{loading?'Saving…':'Save Company Profile'}}</button></form></div></section></template>
