<script setup lang="ts">
definePageMeta({ middleware: ['admin'] })
const supabase=useSupabaseClient(); const rows=ref<any[]>([]); const loading=ref(true); const q=ref(''); const type=ref(''); const approval=ref(''); const errorMessage=ref(''); const successMessage=ref('')
const load=async()=>{loading.value=true; const {data,error}=await supabase.from('companies').select('id,name,type,approved,abn,email,phone,country_code,state_region,city,created_at').order('created_at',{ascending:false}); if(error)errorMessage.value=error.message; rows.value=data||[]; loading.value=false}
const filtered=computed(()=>rows.value.filter(r=>(!type.value||r.type===type.value)&&(!approval.value||(approval.value==='approved'?r.approved:!r.approved))&&(!q.value.trim()||[r.name,r.abn,r.email,r.city].some(v=>String(v||'').toLowerCase().includes(q.value.toLowerCase())))))
const setApproval=async(row:any,approved:boolean)=>{errorMessage.value=''; successMessage.value=''; const {error}=await supabase.rpc('admin_set_company_approval',{p_company_id:row.id,p_approved:approved}); if(error){errorMessage.value=error.message;return} successMessage.value=approved?'Company approved.':'Company approval removed.'; await load()}
onMounted(load)
</script>
<template><section class="section"><div class="container"><div style="display:flex;justify-content:space-between;gap:16px;align-items:end;flex-wrap:wrap"><div><div class="kicker">Administration</div><h1 class="page-title">Companies</h1></div><NuxtLink class="btn btn-secondary" to="/admin">← Dashboard</NuxtLink></div>
<div v-if="errorMessage" class="notice error">{{errorMessage}}</div><div v-if="successMessage" class="notice success">{{successMessage}}</div>
<div class="card grid grid-3" style="padding:18px;margin-top:20px"><input v-model="q" class="input" placeholder="Search company, ABN, email, city"><select v-model="type" class="select"><option value="">All company types</option><option value="supplier">Supplier</option><option value="repairer">Repairer</option></select><select v-model="approval" class="select"><option value="">All approval states</option><option value="pending">Pending</option><option value="approved">Approved</option></select></div>
<div class="card table-wrap" style="margin-top:20px"><table><thead><tr><th>Company</th><th>Type</th><th>Location</th><th>Contact</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-for="row in filtered" :key="row.id"><td><strong>{{row.name}}</strong><br><span class="muted">{{row.abn||'No ABN/business no.'}}</span></td><td><span class="badge">{{row.type}}</span></td><td>{{[row.city,row.state_region,row.country_code].filter(Boolean).join(', ')||'—'}}</td><td>{{row.email||row.phone||'—'}}</td><td><span class="badge" :style="row.approved?'color:#c8ffe4':'color:#ffe4a3'">{{row.approved?'Approved':'Pending'}}</span></td><td><button class="btn small-btn" :class="row.approved?'btn-danger':'btn-primary'" @click="setApproval(row,!row.approved)">{{row.approved?'Remove approval':'Approve'}}</button></td></tr><tr v-if="!loading&&!filtered.length"><td colspan="6" class="muted">No companies found.</td></tr></tbody></table></div>
</div></section></template>
