<script setup lang="ts">
definePageMeta({ middleware: ['admin'] })
const supabase=useSupabaseClient(); const rows=ref<any[]>([]); const q=ref(''); const status=ref(''); const loading=ref(true); const errorMessage=ref(''); const successMessage=ref('')
const load=async()=>{loading.value=true; const {data,error}=await supabase.from('parts').select('id,title,oem_number,price,currency,status,condition,created_at,seller_company_id,companies!parts_seller_company_id_fkey(name)').order('created_at',{ascending:false}).limit(500); if(error)errorMessage.value=error.message; rows.value=data||[]; loading.value=false}
const filtered=computed(()=>rows.value.filter(r=>(!status.value||r.status===status.value)&&(!q.value.trim()||[r.title,r.oem_number,r.companies?.name].some(v=>String(v||'').toLowerCase().includes(q.value.toLowerCase())))))
const setStatus=async(row:any,next:string)=>{const {error}=await supabase.rpc('admin_set_listing_status',{p_part_id:row.id,p_status:next}); if(error){errorMessage.value=error.message;return} successMessage.value='Listing updated.'; await load()}
onMounted(load)
</script>
<template><section class="section"><div class="container"><div style="display:flex;justify-content:space-between;gap:16px;align-items:end;flex-wrap:wrap"><div><div class="kicker">Administration</div><h1 class="page-title">Listings</h1></div><NuxtLink class="btn btn-secondary" to="/admin">← Dashboard</NuxtLink></div><div v-if="errorMessage" class="notice error">{{errorMessage}}</div><div v-if="successMessage" class="notice success">{{successMessage}}</div>
<div class="card grid grid-2" style="padding:18px;margin-top:20px"><input v-model="q" class="input" placeholder="Search title, OEM number or supplier"><select v-model="status" class="select"><option value="">All statuses</option><option v-for="s in ['active','draft','sold','expired','removed']" :key="s" :value="s">{{s}}</option></select></div>
<div class="card table-wrap" style="margin-top:20px"><table><thead><tr><th>Listing</th><th>Supplier</th><th>Condition</th><th>Price</th><th>Status</th><th>Moderation</th></tr></thead><tbody><tr v-for="row in filtered" :key="row.id"><td><NuxtLink :to="`/listings/${row.id}`"><strong>{{row.title}}</strong></NuxtLink><br><span class="muted">{{row.oem_number||'No OEM number'}}</span></td><td>{{row.companies?.name||'—'}}</td><td>{{row.condition}}</td><td>{{row.price!=null?`${row.currency} $${Number(row.price).toFixed(2)}`:'—'}}</td><td><span class="badge">{{row.status}}</span></td><td><select class="select" style="width:auto" :value="row.status" @change="setStatus(row,($event.target as HTMLSelectElement).value)"><option v-for="s in ['active','draft','sold','expired','removed']" :key="s" :value="s">{{s}}</option></select></td></tr><tr v-if="!loading&&!filtered.length"><td colspan="6" class="muted">No listings found.</td></tr></tbody></table></div>
</div></section></template>
