<script setup lang="ts">
definePageMeta({ middleware: ['admin'] })
const supabase=useSupabaseClient(); const rows=ref<any[]>([]); const q=ref(''); const status=ref(''); const loading=ref(true); const errorMessage=ref(''); const successMessage=ref('')
const load=async()=>{loading.value=true; const {data,error}=await supabase.from('wanted_requests').select('id,part_name,oem_number,status,created_at,repairer_company_id,companies!wanted_requests_repairer_company_id_fkey(name),vehicles!wanted_requests_vehicle_id_fkey(year,series,variant,vehicle_makes(name),vehicle_models(name))').order('created_at',{ascending:false}).limit(500); if(error)errorMessage.value=error.message; rows.value=data||[]; loading.value=false}
const filtered=computed(()=>rows.value.filter(r=>(!status.value||r.status===status.value)&&(!q.value.trim()||[r.part_name,r.oem_number,r.companies?.name].some(v=>String(v||'').toLowerCase().includes(q.value.toLowerCase())))))
const setStatus=async(row:any,next:string)=>{const {error}=await supabase.rpc('admin_set_request_status',{p_request_id:row.id,p_status:next}); if(error){errorMessage.value=error.message;return} successMessage.value='Wanted request updated.'; await load()}
onMounted(load)
</script>
<template><section class="section"><div class="container"><div style="display:flex;justify-content:space-between;gap:16px;align-items:end;flex-wrap:wrap"><div><div class="kicker">Administration</div><h1 class="page-title">Wanted Requests</h1></div><NuxtLink class="btn btn-secondary" to="/admin">← Dashboard</NuxtLink></div><div v-if="errorMessage" class="notice error">{{errorMessage}}</div><div v-if="successMessage" class="notice success">{{successMessage}}</div>
<div class="card grid grid-2" style="padding:18px;margin-top:20px"><input v-model="q" class="input" placeholder="Search part, OEM or repairer"><select v-model="status" class="select"><option value="">All statuses</option><option v-for="s in ['open','fulfilled','cancelled','expired']" :key="s" :value="s">{{s}}</option></select></div>
<div class="card table-wrap" style="margin-top:20px"><table><thead><tr><th>Request</th><th>Repairer</th><th>Vehicle</th><th>Status</th><th>Moderation</th></tr></thead><tbody><tr v-for="row in filtered" :key="row.id"><td><strong>{{row.part_name}}</strong><br><span class="muted">{{row.oem_number||'No OEM number'}}</span></td><td>{{row.companies?.name||'—'}}</td><td>{{row.vehicles?[row.vehicles.year,row.vehicles.vehicle_makes?.name,row.vehicles.vehicle_models?.name,row.vehicles.series,row.vehicles.variant].filter(Boolean).join(' '):'—'}}</td><td><span class="badge">{{row.status}}</span></td><td><select class="select" style="width:auto" :value="row.status" @change="setStatus(row,($event.target as HTMLSelectElement).value)"><option v-for="s in ['open','fulfilled','cancelled','expired']" :key="s" :value="s">{{s}}</option></select></td></tr><tr v-if="!loading&&!filtered.length"><td colspan="5" class="muted">No wanted requests found.</td></tr></tbody></table></div>
</div></section></template>
