<script setup lang="ts">
definePageMeta({middleware:['auth','supplier']})
const supabase=useSupabaseClient(); const {company,loadProfile}=useProfile(); const parts=ref<any[]>([]); const loading=ref(true); const errorMessage=ref('')
const load=async()=>{loading.value=true;errorMessage.value='';try{await loadProfile(); if(!company.value?.id) return; const {data,error}=await supabase.from('parts').select('id,title,vehicle_year,vehicle_make,vehicle_model,vehicle_variant,price,currency,quantity,status,created_at,part_images(image_url,sort_order)').eq('seller_company_id',company.value.id).order('created_at',{ascending:false}); if(error)throw error;parts.value=data||[]}catch(e:any){errorMessage.value=e.message}finally{loading.value=false}}
onMounted(load)
const remove=async(id:string)=>{if(!confirm('Delete this part listing?'))return; const {error}=await supabase.from('parts').delete().eq('id',id); if(error){errorMessage.value=error.message;return} parts.value=parts.value.filter(p=>p.id!==id)}
const vehicle=(p:any)=>[p.vehicle_year,p.vehicle_make,p.vehicle_model,p.vehicle_variant].filter(Boolean).join(' ')||'—'
</script>
<template><section class="section"><div class="container"><div style="display:flex;justify-content:space-between;gap:15px;align-items:center;flex-wrap:wrap;"><div><div class="kicker">Supplier inventory</div><h1 class="page-title" style="margin-top:8px;">My Parts</h1></div><NuxtLink to="/supplier/parts/new" class="btn btn-primary">Add Part</NuxtLink></div><div v-if="errorMessage" class="notice error">{{errorMessage}}</div><div v-if="loading" class="card" style="padding:24px;margin-top:22px;">Loading inventory…</div><div v-else-if="!parts.length" class="card empty-state"><h2>No parts listed yet</h2><p class="muted">Add your first part to the Find a Part marketplace.</p><NuxtLink to="/supplier/parts/new" class="btn btn-primary">Add Your First Part</NuxtLink></div><div v-else class="card table-wrap" style="margin-top:22px;padding:8px 18px;"><table><thead><tr><th>Part</th><th>Vehicle</th><th>Price</th><th>Qty</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="part in parts" :key="part.id"><td><div style="display:flex;align-items:center;gap:12px;"><img v-if="part.part_images?.[0]?.image_url" :src="part.part_images[0].image_url" style="width:54px;height:42px;object-fit:cover;border-radius:8px;"><strong>{{part.title}}</strong></div></td><td>{{vehicle(part)}}</td><td>{{part.price==null?'—':`$${Number(part.price).toFixed(2)} ${part.currency}`}}</td><td>{{part.quantity}}</td><td><span class="badge">{{part.status}}</span></td><td><div style="display:flex;gap:8px;"><NuxtLink :to="`/supplier/parts/${part.id}`" class="btn btn-secondary small-btn">Edit</NuxtLink><button class="btn btn-danger small-btn" @click="remove(part.id)">Delete</button></div></td></tr></tbody></table></div></div></section></template>
